name: autodocumentation from sphinx

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinxcontrib-apidoc numpydoc
      - id: deployment
        uses: sphinx-notes/pages@v3
        with: 
          documentation_path: docs
